# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://leoluyi.tw
baseurl: /
title: Leo Lu's Blog
author: Leo Lu
description: Personal website, blog, and curriculum vitae.
avatar: profile.jpg
email: leo0650@gmail.com
github: leoluyi # username
twitter: leo_luyi
linkedin: leoluyi
medium: leoluyi
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: leoluyi
google_analytics: UA-515255-3


# needed for travis-ci build
exclude: [vendor]

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

